#!/bin/sh

dir="$(dirname $0)"
find "${dir}/tests" -name "test_*" | sort | while read t
do
  echo "<<<<<<<< ${t} >>>>>>>>"
  "${dir}/tools/run_test" "${t}"
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
