#!/bin/sh

. "${1}"

dir="$(dirname $0)"
slave="${dir}/slave/slave"
cmd="${dir}/${exe}/${exe}"
"${slave}" "${cmd}" ${params}
status="$?"

type test_status > /dev/null
if [ "$?" -eq 0 ]; then
  test_status "${status}"
  if [ "$?" -eq 0 ]; then
    okng="OK"
  else
    okng="NG"
  fi
  echo "${1}: ${okng}"
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
